Fix multiple calls to Model.Verify() resulting in duplicate property names in generated error paths.
JohannesMoersch/Valigator pull request #42
Opened 2020-11-05 20:41 UTC by NathanMagnus

2020-11-05 21:15 UTC, NathanMagnus commented
@JohannesMoersch I'm not overly familiar with the entire workings of Valigator, but this fixes the issue I'm running into. I'm not sure if you are concerned with causing errors somewhere else.

The root cause of the issue is that each time Verify is called, it adds the property onto the `Path` (through the `Model.AddPropertyToErrors` method).

2020-11-05 21:17 UTC, NathanMagnus commented on Valigator.TestApi.Core31/Controllers/TestController.cs
> +		public Data<InnerClass[]> IdentifierCollection { get; set; } = Data.Collection<InnerClass>().Required().ItemCount(1, 1);
Makes for easier testing of the issue I was hunting down. I can revert this type of change if you are concerned with it.

2020-11-05 21:17 UTC, NathanMagnus commented on Valigator.TestApi.Core31/Startup.cs
> +	internal class NullObjectModelValidator : IObjectModelValidator
This stops the Asp.Net Core model validation from running when registered. This is essential to replicate the error I was having.

2020-11-05 21:20 UTC, NathanMagnus commented on Valigator.Core/Valigator.Core.csproj
> +    <Version>2.0.1</Version>
Do I need to update version anywhere else to update the version of the other packages?

2020-11-06 15:28 UTC, JohannesMoersch commented
Tests still pass so I believe the modified solution should fix your problem.

2020-11-06 15:37 UTC, NathanMagnus commented
This one I tested both with the unit tests and manually to make sure it works.

I just tested manually and your changes still work. I am satisfied with this solution.

2020-11-06 16:25 UTC, JohannesMoersch approved these changes

2020-11-06 16:26 UTC, JohannesMoersch requested changes
Versioning needs to change. I'll do it. 1 sec

2020-11-06 16:29 UTC, JohannesMoersch approved these changes

2020-11-06 16:29 UTC, JohannesMoersch commented
There's a root directory.props file that has the version in it.

2020-11-06 16:30 UTC, merged